---
- name: Jenkins installation
  hosts: jenkins
  tasks:
   - name: Get the jenkins repository key to system
     ansible.builtin.apt_key:
      url: "{{ repository_key_url }}"

   - name: Add jenkins apt repository
     ansible.builtin.apt_repository:
      repo: "deb {{ repository_url }} binary/"
      filename: jenkins

   - name: Install java and jenkins
      ansible.builtin.package:
        name: "{{ item }}"
        update_cache: true
      loop: "{{ install_packages }}"

   - name: Start jenkins.service
     ansible.builtin.systemd_service:
      name: "jenkins"
      state: started
      enabled: true
