all:
  children:
    masternode:
      hosts:
        host1:

    workers:
      hosts:
        host2:
        host3:


    k8s_tools:
      children:
        masternode:
        workers:

    crio:
      children:
        masternode:
        workers:

    jenkins:
      children:
        masternode:
