// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/repository.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// IsCurrencyExist mocks base method.
func (m *MockRepository) IsCurrencyExist(ISOName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCurrencyExist", ISOName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCurrencyExist indicates an expected call of IsCurrencyExist.
func (mr *MockRepositoryMockRecorder) IsCurrencyExist(ISOName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCurrencyExist", reflect.TypeOf((*MockRepository)(nil).IsCurrencyExist), ISOName)
}

// WriteCurrency mocks base method.
func (m *MockRepository) WriteCurrency(ISOName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteCurrency", ISOName)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteCurrency indicates an expected call of WriteCurrency.
func (mr *MockRepositoryMockRecorder) WriteCurrency(ISOName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteCurrency", reflect.TypeOf((*MockRepository)(nil).WriteCurrency), ISOName)
}
