- name: Start crio service
  ansible.builtin.service:
    name: crio
    state: started

- name: Removing swapfile from /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: Load br_netfilter module
  ansible.builtin.modprobe:
    name: br_netfilter

- name: Enable IP forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
